### ISSUE TITLE
[Fiche 1] La solution en position:absolute prend toute la page

### ISSUE THREAD

**Issue by borisschapira** [TrainDrop/fiches#5]
http://codepen.io/borisschapira/pen/YPQWgZ

**Comment by Twikito** [comment]
Oui, parce que le code est pas bon.

**Comment by Twikito** [comment]
Voilà m'sieur :)
http://codepen.io/Twikito/pen/mywEYB

**Comment by borisschapira** [comment]
Pfff, le pire c'est que je l'ai écris dans les slides que j'ai présenté juste avant... "Positionnement absolu : un élément qui se fiche complètement des autres et se positionne par rapport à l'élément parent en position relative".

Et juste après j'oublie de mettre le parent en relative...

Je corrige la fiche pour que ce soit plus clair.

**Comment by borisschapira** [comment]
Merci !
